export const pokemons = [
	{
		id: "UG9rZt1vbjowMzA=",
		number: "001",
		name: "Bulbasaur",
		classification: "Seed Pokemon",
		fleeRate: 0.01,
		image: "https://img.pokemondb.net/artwork/bulbasaur.jpg",
	},
	{
		id: "UGzraW1vbjowMzA=",
		number: "002",
		name: "Ivysaur",
		classification: "Seed Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/ivysaur.jpg",
	},
	{
		id: "UG9rZW1vbjbomMzA=",
		number: "003",
		name: "Venusaur",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.03,
		image: "https://img.pokemondb.net/artwork/venusaur.jpg",
	},
	{
		id: "UG9rZW1vbjmwMzA=",
		number: "004",
		name: "Charmander",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/charmander.jpg",
	},
	{
		id: "UG9rbW1vbjowMzA=",
		number: "005",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.03,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9zZW1vbjowMzA=",
		number: "006",
		name: "Pikachu",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/pikachu.jpg",
	},
	{
		id: "UG9rZWcvbjowMzA=",
		number: "007",
		name: "Gengar",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.01,
		image: "https://img.pokemondb.net/artwork/gengar.jpg",
	},
	{
		id: "UG9rZW1vbsowMzA=",
		number: "008",
		name: "Gyarados",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/gyarados.jpg",
	},
	{
		id: "UG9rZW1vdjowMzA=",
		number: "009",
		name: "Eevee",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.05,
		image: "https://img.pokemondb.net/artwork/eevee.jpg",
	},
	{
		id: "UG9rZW1vbaowMzA=",
		number: "010",
		name: "Dragonite",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/dragonite.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "011",
		name: "Tyranitar",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/tyranitar.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "012",
		name: "Garchomp",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.01,
		image: "https://img.pokemondb.net/artwork/garchomp.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "013",
		name: "Lucario",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.05,
		image: "https://img.pokemondb.net/artwork/lucario.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "014",
		name: "Corviknight",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/corviknight.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "015",
		name: "Toxtricity",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/toxtricity.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "016",
		name: "Dragapult",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/dragapult.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "017",
		name: "Charmeleon",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.01,
		image: "https://img.pokemondb.net/artwork/charmeleon.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "018",
		name: "Charizard",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.05,
		image: "https://img.pokemondb.net/artwork/charizard.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "019",
		name: "Pupitar",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/pupitar.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "020",
		name: "Tyranitar",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.03,
		image: "https://img.pokemondb.net/artwork/tyranitar.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "021",
		name: "Larvitar",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.05,
		image: "https://img.pokemondb.net/artwork/larvitar.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "022",
		name: "Toxtricity",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/toxtricity.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "023",
		name: "Toxel",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/toxel.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "024",
		name: "Gible",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.07,
		image: "https://img.pokemondb.net/artwork/gible.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "025",
		name: "Garchomp",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.06,
		image: "https://img.pokemondb.net/artwork/garchomp.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "026",
		name: "Jolteon",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.05,
		image: "https://img.pokemondb.net/artwork/jolteon.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "027",
		name: "Espeon",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/espeon.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "028",
		name: "Umbreon",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.03,
		image: "https://img.pokemondb.net/artwork/umbreon.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "029",
		name: "Sylveon",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/sylveon.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "030",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.01,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
];
