export const pokemons = [
	{
		id: "UG9rZt1vbjowMzA=",
		number: "001",
		name: "Bulbasaur",
		classification: "Seed Pokemon",
		fleeRate: 0.01,
		image: "https://img.pokemondb.net/artwork/bulbasaur.jpg",
	},
	{
		id: "UGzraW1vbjowMzA=",
		number: "002",
		name: "Ivysaur",
		classification: "Seed Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/ivysaur.jpg",
	},
	{
		id: "UG9rZW1vbjbomMzA=",
		number: "003",
		name: "Venusaur",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.03,
		image: "https://img.pokemondb.net/artwork/venusaur.jpg",
	},
	{
		id: "UG9rZW1vbjmwMzA=",
		number: "004",
		name: "Charmander",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/charmander.jpg",
	},
	{
		id: "UG9rbW1vbjowMzA=",
		number: "005",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.03,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9zZW1vbjowMzA=",
		number: "006",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZWcvbjowMzA=",
		number: "007",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.01,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbsowMzA=",
		number: "008",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vdjowMzA=",
		number: "009",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.05,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbaowMzA=",
		number: "010",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "011",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "012",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.01,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "013",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.05,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "014",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "015",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "016",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "017",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.01,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "018",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.05,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "019",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "020",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.03,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "021",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.05,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "022",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "023",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "024",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.07,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "025",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.06,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "026",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.05,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "027",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.04,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "028",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.03,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "029",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.02,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
	{
		id: "UG9rZW1vbjosMzA=",
		number: "030",
		name: "Nidorina",
		classification: "Poison Pin Pokemon",
		fleeRate: 0.01,
		image: "https://img.pokemondb.net/artwork/nidorina.jpg",
	},
];
